compile:
	export CLASSPATH=".:/usr/local/lib/antlr-4.9.2-complete.jar:";
	alias antlr='java -jar /usr/local/lib/antlr-4.9.2-complete.jar';
	alias grun='java org.antlr.v4.runtime.misc.TestRig';

	java -jar /usr/local/lib/antlr-4.9.2-complete.jar -Dlanguage=Python3 simba.g4
	pygrun simba start --tree ../tests/test1.sb 
	# tree or tokens

